import type { Scholarship } from "@/lib/api-types";

export const MOCK_SCHOLARSHIPS: Scholarship[] = [
  {
    id: "1",
    nama: "LPDP Reguler",
    provider: "Lembaga Pengelola Dana Pendidikan (LPDP)",
    deskripsi:
      "Beasiswa LPDP Reguler adalah program beasiswa penuh dari pemerintah Indonesia yang ditujukan untuk putra-putri terbaik bangsa yang ingin melanjutkan studi S2 atau S3 di dalam maupun luar negeri. Program ini bertujuan untuk menyiapkan pemimpin dan profesional masa depan Indonesia.",
    persyaratan: [
      "Warga Negara Indonesia",
      "Tidak sedang menempuh studi S2/S3",
      "IPK S1 minimal 3.00 (skala 4.00)",
      "Usia maksimal 35 tahun untuk S2, 40 tahun untuk S3",
      "Sertifikat bahasa Inggris TOEFL iBT minimal 80 atau IELTS minimal 6.5",
      "Surat rekomendasi dari atasan atau akademisi",
      "Essay motivasi dan rencana kontribusi",
    ],
    benefit: [
      "Biaya pendidikan penuh (tuition fee)",
      "Biaya hidup bulanan",
      "Biaya transportasi keberangkatan dan kepulangan",
      "Biaya buku dan penelitian",
      "Asuransi kesehatan",
      "Biaya visa dan akomodasi kedatangan",
    ],
    deadline: "2025-10-31",
    link_pendaftaran: "https://beasiswalpdp.kemenkeu.go.id",
    tipe_pembiayaan: "Penuh",
    negara: "Indonesia",
    is_active: true,
    universitas: [
      {
        university_id: "uni-1",
        nama: "Universitas Indonesia",
        kota: "Depok",
        negara: "Indonesia",
        ranking: 237,
        website: "https://www.ui.ac.id",
        tipe: "public",
        deskripsi: "Universitas tertua dan bergengsi di Indonesia, berlokasi di Depok.",
      },
      {
        university_id: "uni-2",
        nama: "Institut Teknologi Bandung",
        kota: "Bandung",
        negara: "Indonesia",
        ranking: 303,
        website: "https://www.itb.ac.id",
        tipe: "public",
        deskripsi: "Institut teknologi terkemuka di Indonesia dengan fokus sains dan teknik.",
      },
      {
        university_id: "uni-3",
        nama: "Universitas Gadjah Mada",
        kota: "Yogyakarta",
        negara: "Indonesia",
        ranking: 254,
        website: "https://www.ugm.ac.id",
        tipe: "public",
        deskripsi: "Universitas negeri terkemuka di Indonesia, berlokasi di Yogyakarta.",
      },
    ],
  },
  {
    id: "2",
    nama: "Chevening Scholarship",
    provider: "UK Government (Foreign, Commonwealth & Development Office)",
    deskripsi:
      "Chevening adalah program beasiswa prestisius dari pemerintah Inggris yang memberikan kesempatan kepada para pemimpin masa depan dari seluruh dunia untuk belajar di universitas terbaik di Inggris. Program ini mencakup gelar master satu tahun di universitas mana pun di Inggris.",
    persyaratan: [
      "Warga negara dari negara yang memenuhi syarat Chevening",
      "Telah menyelesaikan pendidikan S1",
      "Memiliki minimal 2 tahun pengalaman kerja",
      "Kembali ke negara asal minimal 2 tahun setelah studi",
      "Memenuhi persyaratan bahasa Inggris universitas tujuan",
      "Belum pernah menerima beasiswa Chevening sebelumnya",
    ],
    benefit: [
      "Biaya kuliah penuh",
      "Tunjangan hidup bulanan",
      "Tiket pesawat pulang-pergi",
      "Tunjangan kedatangan",
      "Biaya visa Inggris",
      "Akses jaringan alumni Chevening global",
    ],
    deadline: "2025-11-05",
    link_pendaftaran: "https://www.chevening.org/scholarships",
    tipe_pembiayaan: "Penuh",
    negara: "United Kingdom",
    is_active: true,
    universitas: [
      {
        university_id: "uni-4",
        nama: "University of Oxford",
        kota: "Oxford",
        negara: "United Kingdom",
        ranking: 1,
        website: "https://www.ox.ac.uk",
        tipe: "public",
        deskripsi: "Salah satu universitas tertua dan paling bergengsi di dunia.",
      },
      {
        university_id: "uni-5",
        nama: "University of Cambridge",
        kota: "Cambridge",
        negara: "United Kingdom",
        ranking: 2,
        website: "https://www.cam.ac.uk",
        tipe: "public",
        deskripsi: "Universitas riset terkemuka dengan tradisi akademik lebih dari 800 tahun.",
      },
      {
        university_id: "uni-6",
        nama: "Imperial College London",
        kota: "London",
        negara: "United Kingdom",
        ranking: 6,
        website: "https://www.imperial.ac.uk",
        tipe: "public",
        deskripsi: "Universitas sains, teknik, kedokteran, dan bisnis terkemuka di London.",
      },
    ],
  },
  {
    id: "3",
    nama: "Fulbright Indonesian Student Program",
    provider: "American Indonesian Exchange Foundation (AMINEF)",
    deskripsi:
      "Program beasiswa Fulbright untuk mahasiswa Indonesia yang ingin melanjutkan studi S2 atau S3 di Amerika Serikat. Program ini merupakan bagian dari program pertukaran internasional yang disponsori oleh pemerintah Amerika Serikat.",
    persyaratan: [
      "Warga Negara Indonesia",
      "IPK S1 minimal 3.0 pada skala 4.0",
      "TOEFL ITP minimal 550 atau TOEFL iBT minimal 80 atau IELTS 6.5",
      "Tidak pernah atau sedang tinggal di AS lebih dari 5 tahun",
      "Berkomitmen kembali ke Indonesia setelah studi",
      "Pengalaman kepemimpinan dan kontribusi masyarakat",
    ],
    benefit: [
      "Biaya kuliah dan biaya akademik lainnya",
      "Tunjangan biaya hidup bulanan",
      "Asuransi kesehatan dan kecelakaan",
      "Tiket pesawat pulang-pergi",
      "Program orientasi pra-keberangkatan",
      "Jaringan alumni Fulbright internasional",
    ],
    deadline: "2025-09-15",
    link_pendaftaran: "https://www.aminef.or.id/grants-for-indonesians/fulbright-programs",
    tipe_pembiayaan: "Penuh",
    negara: "United States",
    is_active: true,
    universitas: [
      {
        university_id: "uni-7",
        nama: "Massachusetts Institute of Technology",
        kota: "Cambridge, MA",
        negara: "United States",
        ranking: 1,
        website: "https://www.mit.edu",
        tipe: "private",
        deskripsi: "Institut teknologi terkemuka dunia dengan riset inovatif.",
      },
      {
        university_id: "uni-8",
        nama: "Stanford University",
        kota: "Stanford, CA",
        negara: "United States",
        ranking: 3,
        website: "https://www.stanford.edu",
        tipe: "private",
        deskripsi: "Universitas riset swasta terkemuka di Silicon Valley.",
      },
    ],
  },
  {
    id: "4",
    nama: "DAAD Scholarship",
    provider: "Deutscher Akademischer Austauschdienst (DAAD)",
    deskripsi:
      "Beasiswa DAAD adalah program beasiswa dari lembaga pertukaran akademis Jerman yang menawarkan berbagai program studi di universitas-universitas terbaik Jerman. Program ini mendukung kerjasama internasional antara Jerman dan negara-negara di seluruh dunia.",
    persyaratan: [
      "Sarjana dengan gelar yang sangat baik (minimal IPK 3.0)",
      "Kemampuan bahasa Jerman atau Inggris sesuai program",
      "Tidak lebih dari 6 tahun sejak lulus S1",
      "Pengalaman kerja profesional minimal 2 tahun (beberapa program)",
      "Surat motivasi dan rencana studi",
      "Dua surat rekomendasi akademis",
    ],
    benefit: [
      "Tunjangan bulanan €934 untuk mahasiswa S2",
      "Tunjangan bulanan €1.200 untuk mahasiswa S3",
      "Subsidi perjalanan",
      "Asuransi kesehatan, kecelakaan, dan pribadi",
      "Tunjangan sewa (tergantung program)",
      "Kursus bahasa Jerman intensif",
    ],
    deadline: "2025-10-15",
    link_pendaftaran: "https://www.daad.de/en/study-and-research-in-germany/scholarships",
    tipe_pembiayaan: "Penuh",
    negara: "Germany",
    is_active: true,
    universitas: [
      {
        university_id: "uni-9",
        nama: "Technical University of Munich",
        kota: "Munich",
        negara: "Germany",
        ranking: 37,
        website: "https://www.tum.de",
        tipe: "public",
        deskripsi: "Universitas teknik terbaik di Jerman dengan reputasi internasional.",
      },
      {
        university_id: "uni-10",
        nama: "Heidelberg University",
        kota: "Heidelberg",
        negara: "Germany",
        ranking: 42,
        website: "https://www.uni-heidelberg.de",
        tipe: "public",
        deskripsi: "Universitas tertua di Jerman, didirikan pada tahun 1386.",
      },
    ],
  },
  {
    id: "5",
    nama: "Australia Awards Scholarship",
    provider: "Australian Government – Department of Foreign Affairs and Trade",
    deskripsi:
      "Australia Awards memberikan kesempatan bagi warga negara dari negara-negara berkembang, termasuk Indonesia, untuk melakukan studi, penelitian, dan pengembangan profesional di Australia. Program ini bertujuan berkontribusi pada pembangunan berkelanjutan.",
    persyaratan: [
      "Warga Negara Indonesia berusia minimal 18 tahun",
      "Tidak memiliki kewarganegaraan Australia atau sedang dalam proses aplikasi",
      "IPK minimal 2.9 dari skala 4.0",
      "IELTS minimal 6.0 (setiap band minimal 5.0)",
      "Minimal 2 tahun pengalaman kerja penuh waktu",
      "Berkomitmen kembali ke Indonesia setelah studi",
    ],
    benefit: [
      "Biaya kuliah penuh",
      "Tunjangan hidup per dua minggu",
      "Tiket pesawat ekonomi kelas dari Indonesia ke Australia (PP)",
      "Biaya Overseas Student Health Cover (OSHC)",
      "Program penguatan akademik pra-keberangkatan",
      "Kursus bahasa Inggris intensif jika diperlukan",
    ],
    deadline: "2025-04-30",
    link_pendaftaran: "https://www.australiaawardsindonesia.org",
    tipe_pembiayaan: "Penuh",
    negara: "Australia",
    is_active: true,
    universitas: [
      {
        university_id: "uni-11",
        nama: "University of Melbourne",
        kota: "Melbourne",
        negara: "Australia",
        ranking: 13,
        website: "https://www.unimelb.edu.au",
        tipe: "public",
        deskripsi: "Universitas riset terkemuka di Australia dengan program akademik beragam.",
      },
      {
        university_id: "uni-12",
        nama: "Australian National University",
        kota: "Canberra",
        negara: "Australia",
        ranking: 30,
        website: "https://www.anu.edu.au",
        tipe: "public",
        deskripsi: "Universitas nasional Australia yang berfokus pada kebijakan publik dan riset.",
      },
    ],
  },
  {
    id: "6",
    nama: "Erasmus Mundus Joint Master Degrees",
    provider: "European Commission",
    deskripsi:
      "Erasmus Mundus Joint Master Degrees (EMJMD) adalah program beasiswa bergengsi dari Uni Eropa untuk studi S2 di konsorsium universitas-universitas Eropa terbaik. Program ini memberikan pengalaman belajar di dua atau lebih negara Eropa.",
    persyaratan: [
      "Gelar sarjana atau yang setara",
      "Kemampuan bahasa Inggris yang memadai",
      "Warga negara non-Uni Eropa (untuk beasiswa penuh)",
      "Tidak pernah tinggal di salah satu negara konsorsium lebih dari 12 bulan selama 5 tahun terakhir",
      "Memenuhi persyaratan spesifik program yang dipilih",
    ],
    benefit: [
      "Biaya kuliah penuh (hingga €9.000/tahun)",
      "Tunjangan hidup bulanan €1.000",
      "Kontribusi perjalanan €3.000 (hingga €5.000 untuk jarak jauh)",
      "Asuransi",
      "Gelar dari minimal dua universitas berbeda",
      "Jaringan alumni Erasmus internasional",
    ],
    deadline: "2026-01-15",
    link_pendaftaran: "https://www.eacea.ec.europa.eu/scholarships/emjmd-catalogue",
    tipe_pembiayaan: "Penuh",
    negara: "Europe",
    is_active: true,
    universitas: [
      {
        university_id: "uni-13",
        nama: "KU Leuven",
        kota: "Leuven",
        negara: "Belgium",
        ranking: 45,
        website: "https://www.kuleuven.be",
        tipe: "public",
        deskripsi: "Universitas riset Katolik terkemuka di Belgia.",
      },
      {
        university_id: "uni-14",
        nama: "Uppsala University",
        kota: "Uppsala",
        negara: "Sweden",
        ranking: 91,
        website: "https://www.uu.se",
        tipe: "public",
        deskripsi: "Universitas tertua di Skandinavia, didirikan tahun 1477.",
      },
    ],
  },
  {
    id: "7",
    nama: "ADB-JSP Scholarship",
    provider: "Asian Development Bank – Japan Scholarship Program",
    deskripsi:
      "Program beasiswa Asian Development Bank-Japan Scholarship Program (ADB-JSP) menyediakan kesempatan kepada warga negara anggota berkembang ADB untuk menempuh studi S2 dan S3 di universitas-universitas bergengsi di kawasan Asia dan Pasifik.",
    persyaratan: [
      "Warga negara dari negara anggota berkembang ADB",
      "Gelar sarjana dengan IPK yang baik",
      "Minimal 2 tahun pengalaman kerja profesional setelah S1",
      "Usia tidak lebih dari 35 tahun",
      "Kemampuan bahasa Inggris yang memadai",
      "Tidak menerima beasiswa lain pada saat yang bersamaan",
    ],
    benefit: [
      "Biaya kuliah penuh",
      "Tunjangan hidup bulanan",
      "Tunjangan buku dan bahan akademis",
      "Asuransi kesehatan",
      "Tiket pesawat ekonomi PP",
      "Kursus bahasa Inggris pra-studi (jika diperlukan)",
    ],
    deadline: "2025-08-31",
    link_pendaftaran: "https://www.adb.org/site/careers/japan-scholarship-program",
    tipe_pembiayaan: "Penuh",
    negara: "Japan",
    is_active: true,
    universitas: [
      {
        university_id: "uni-15",
        nama: "University of Tokyo",
        kota: "Tokyo",
        negara: "Japan",
        ranking: 23,
        website: "https://www.u-tokyo.ac.jp",
        tipe: "public",
        deskripsi: "Universitas riset paling bergengsi di Jepang.",
      },
    ],
  },
  {
    id: "8",
    nama: "Beasiswa Unggulan Kemendikbud",
    provider: "Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi RI",
    deskripsi:
      "Beasiswa Unggulan adalah program beasiswa dari Kemendikbudristek yang diberikan kepada putra-putri terbaik bangsa Indonesia yang berprestasi untuk melanjutkan pendidikan S1, S2, atau S3 di perguruan tinggi dalam negeri maupun luar negeri.",
    persyaratan: [
      "Warga Negara Indonesia",
      "Diterima di perguruan tinggi terakreditasi",
      "IPK minimal 3.25 untuk S2/S3",
      "Berprestasi di bidang akademik atau non-akademik",
      "Belum pernah menempuh jenjang pendidikan yang sama",
      "Surat rekomendasi dari dosen/atasan",
    ],
    benefit: [
      "Biaya pendidikan (SPP/UKT) sesuai standar",
      "Biaya hidup bulanan",
      "Biaya penelitian dan penulisan karya tulis",
      "Biaya seminar/konferensi (S3)",
      "Biaya transportasi keberangkatan dan kepulangan (luar negeri)",
    ],
    deadline: "2025-07-31",
    link_pendaftaran: "https://beasiswaunggulan.kemdikbud.go.id",
    tipe_pembiayaan: "Penuh",
    negara: "Indonesia",
    is_active: true,
    universitas: [
      {
        university_id: "uni-1",
        nama: "Universitas Indonesia",
        kota: "Depok",
        negara: "Indonesia",
        ranking: 237,
        website: "https://www.ui.ac.id",
        tipe: "public",
        deskripsi: "Universitas tertua dan bergengsi di Indonesia.",
      },
      {
        university_id: "uni-16",
        nama: "Universitas Airlangga",
        kota: "Surabaya",
        negara: "Indonesia",
        ranking: 465,
        website: "https://www.unair.ac.id",
        tipe: "public",
        deskripsi: "Universitas negeri terkemuka di Surabaya.",
      },
    ],
  },
  {
    id: "9",
    nama: "NUS Research Scholarship",
    provider: "National University of Singapore",
    deskripsi:
      "NUS Research Scholarship diberikan kepada mahasiswa internasional berbakat yang ingin mengejar gelar PhD di National University of Singapore. Penerima beasiswa akan terlibat dalam penelitian mutakhir di bawah bimbingan akademisi terkemuka dunia.",
    persyaratan: [
      "Gelar S1 atau S2 dengan hasil sangat baik",
      "Kemampuan bahasa Inggris: TOEFL iBT 85+ atau IELTS 6.0+",
      "Diterima dalam program PhD di NUS",
      "Proposal penelitian yang kuat",
      "Surat rekomendasi dari akademisi terkemuka",
    ],
    benefit: [
      "Biaya kuliah penuh selama masa studi",
      "Tunjangan bulanan SGD 2.000 (S1) atau SGD 2.500 (S2)",
      "Tunjangan komputer sekali bayar SGD 1.500",
      "Asuransi kesehatan",
      "Subsidi akomodasi kampus",
    ],
    deadline: "2025-12-15",
    link_pendaftaran: "https://nus.edu.sg/admissions/graduate/scholarships",
    tipe_pembiayaan: "Penuh",
    negara: "Singapore",
    is_active: true,
    universitas: [
      {
        university_id: "uni-17",
        nama: "National University of Singapore",
        kota: "Singapore",
        negara: "Singapore",
        ranking: 8,
        website: "https://www.nus.edu.sg",
        tipe: "public",
        deskripsi: "Universitas riset terkemuka di Asia dengan reputasi global.",
      },
    ],
  },
  {
    id: "10",
    nama: "Gates Cambridge Scholarship",
    provider: "Gates Cambridge Trust",
    deskripsi:
      "Gates Cambridge Scholarship adalah salah satu program beasiswa paling bergengsi di dunia, diberikan kepada mahasiswa internasional berprestasi luar biasa untuk melanjutkan gelar postgraduate di University of Cambridge. Program ini didanai oleh Bill & Melinda Gates Foundation.",
    persyaratan: [
      "Warga negara di luar Inggris",
      "Mendaftar ke salah satu dari tiga program gelar penuh di Cambridge: PhD, MSc/MLitt, atau One-year postgraduate course",
      "Bukti prestasi intelektual luar biasa",
      "Kepemimpinan dan komitmen terhadap peningkatan kehidupan orang lain",
      "Komitmen untuk belajar di Cambridge",
    ],
    benefit: [
      "Biaya kuliah penuh",
      "Tunjangan pemeliharaan (biaya hidup)",
      "Tiket pesawat ke dan dari Cambridge",
      "Tunjangan visa dan imigrasi",
      "Biaya keluarga (dalam kondisi tertentu)",
      "Tunjangan pengembangan akademik",
    ],
    deadline: "2025-10-08",
    link_pendaftaran: "https://www.gatescambridge.org/apply",
    tipe_pembiayaan: "Penuh",
    negara: "United Kingdom",
    is_active: true,
    universitas: [
      {
        university_id: "uni-5",
        nama: "University of Cambridge",
        kota: "Cambridge",
        negara: "United Kingdom",
        ranking: 2,
        website: "https://www.cam.ac.uk",
        tipe: "public",
        deskripsi: "Universitas riset terkemuka dengan tradisi akademik lebih dari 800 tahun.",
      },
    ],
  },
  {
    id: "11",
    nama: "Monbukagakusho (MEXT) Scholarship",
    provider: "Ministry of Education, Culture, Sports, Science and Technology of Japan",
    deskripsi:
      "Beasiswa Monbukagakusho (MEXT) adalah program beasiswa dari pemerintah Jepang yang memberikan kesempatan kepada mahasiswa internasional untuk belajar di universitas-universitas Jepang. Program ini mencakup berbagai jenjang mulai dari S1 hingga S3.",
    persyaratan: [
      "Warga negara yang memiliki hubungan diplomatik dengan Jepang",
      "IPK minimal 2.3 dari skala 3.0 atau setara",
      "Usia 17-25 tahun (S1) atau hingga 35 tahun (S2/S3)",
      "Kesehatan yang baik secara fisik dan mental",
      "Minat terhadap budaya dan bahasa Jepang",
    ],
    benefit: [
      "Biaya kuliah penuh (termasuk biaya seleksi dan ujian)",
      "Tunjangan bulanan ¥117.000 (S1), ¥144.000 (S2/S3)",
      "Tiket pesawat kelas ekonomi PP",
      "Kursus bahasa Jepang sebelum memulai studi",
      "Asuransi kecelakaan",
    ],
    deadline: "2025-05-31",
    link_pendaftaran: "https://www.id.emb-japan.go.jp/sch_rs2.html",
    tipe_pembiayaan: "Penuh",
    negara: "Japan",
    is_active: true,
    universitas: [
      {
        university_id: "uni-15",
        nama: "University of Tokyo",
        kota: "Tokyo",
        negara: "Japan",
        ranking: 23,
        website: "https://www.u-tokyo.ac.jp",
        tipe: "public",
        deskripsi: "Universitas riset paling bergengsi di Jepang.",
      },
      {
        university_id: "uni-18",
        nama: "Kyoto University",
        kota: "Kyoto",
        negara: "Japan",
        ranking: 46,
        website: "https://www.kyoto-u.ac.jp",
        tipe: "public",
        deskripsi: "Universitas riset terkemuka kedua di Jepang.",
      },
    ],
  },
  {
    id: "12",
    nama: "Beasiswa Bank Indonesia",
    provider: "Bank Indonesia",
    deskripsi:
      "Beasiswa Bank Indonesia (BI) adalah program beasiswa yang diberikan kepada mahasiswa berprestasi di seluruh Indonesia yang sedang menempuh pendidikan S1 maupun S2. Program ini bertujuan untuk mendukung generasi muda Indonesia dalam pengembangan ilmu ekonomi dan keuangan.",
    persyaratan: [
      "Warga Negara Indonesia",
      "Mahasiswa aktif perguruan tinggi terakreditasi",
      "IPK minimal 3.00 untuk S1, 3.25 untuk S2",
      "Semester 3 keatas (S1) atau Semester 1 (S2)",
      "Tidak menerima beasiswa lain",
      "Aktif dalam kegiatan kemahasiswaan",
    ],
    benefit: [
      "Biaya hidup bulanan",
      "Biaya buku dan referensi",
      "Program pengembangan kompetensi",
      "Networking dengan alumni penerima beasiswa BI",
      "Peluang magang di Bank Indonesia",
    ],
    deadline: "2025-06-30",
    link_pendaftaran: "https://www.bi.go.id/id/tentang-bi/beasiswa/Contents/Default.aspx",
    tipe_pembiayaan: "Parsial",
    negara: "Indonesia",
    is_active: true,
    universitas: [
      {
        university_id: "uni-1",
        nama: "Universitas Indonesia",
        kota: "Depok",
        negara: "Indonesia",
        ranking: 237,
        website: "https://www.ui.ac.id",
        tipe: "public",
        deskripsi: "Universitas tertua dan bergengsi di Indonesia.",
      },
      {
        university_id: "uni-2",
        nama: "Institut Teknologi Bandung",
        kota: "Bandung",
        negara: "Indonesia",
        ranking: 303,
        website: "https://www.itb.ac.id",
        tipe: "public",
        deskripsi: "Institut teknologi terkemuka di Indonesia.",
      },
      {
        university_id: "uni-3",
        nama: "Universitas Gadjah Mada",
        kota: "Yogyakarta",
        negara: "Indonesia",
        ranking: 254,
        website: "https://www.ugm.ac.id",
        tipe: "public",
        deskripsi: "Universitas negeri terkemuka di Indonesia.",
      },
    ],
  },
];
